
name: Run tests and linting

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019] #, macos-11]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install build dependencies
        run: pip install oldest-supported-numpy
      - name: Cache GHC stuff
        uses:  actions/cache@v3
        with:
          path: |
            .hsbuild
          key: ${{ runner.os }}-${{ hashFiles('setup.py') }}
      - name: Prepare GHC
        run: python setup.py prepare_haskell
      - name: Build and install the package
        run: python setup.py install
      - name: Run tests
        run: pip install pytest; pytest