
name: Run tests and linting

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install build dependencies
        run: pip install "oldest-supported-numpy;python_version>'3.7'" "numpy==1.16;python_version<='3.7'"
      - name: Cache GHC stuff
        uses:  actions/cache@v3
        with:
          path: |
            .hsbuild
          key: ${{ runner.os }}-${{ hashFiles('setup.py') }}
      - name: Prepare GHC
        run: python setup.py prepare_haskell
      - name: Build and install the package
        run: python setup.py install
      - name: Run tests
        run: pip install pytest; pytest
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled && failure() }}
        with:
          limit-access-to-actor: true